version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - pgadmin

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: douglas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"

  migration-generator:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "cd /app && npm install -g typescript && npm run migration:generate && tsc src/toAlterMigrations.ts && sleep 30 && node src/toAlterMigrations.js && npm run migration:run"
    environment:
      - DATABASE_HOST=postgres
      # Outras variáveis de ambiente necessárias para suas migrações
    depends_on:
      - postgres